# Generated by Django 3.2.13 on 2022-11-22 00:55

import collectdata.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('base_file', models.FileField(upload_to='mydocs/', validators=[collectdata.validators.validate_file_size, collectdata.validators.validate_file_extention], verbose_name='base_file')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rows_num', models.IntegerField(blank=True, null=True)),
                ('cols_num', models.IntegerField(blank=True, null=True)),
                ('nulls_num', models.IntegerField(blank=True, null=True)),
                ('duplicates_num', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_data', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectdata.basedata')),
            ],
        ),
    ]
