# Generated by Django 3.2.13 on 2022-08-21 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0003_auto_20220821_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedata',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
