# Generated by Django 3.2.13 on 2022-08-21 16:46

import collectdata.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0004_basedata_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedata',
            name='base_file',
            field=models.FileField(upload_to='mydocs/', validators=[collectdata.validators.validate_file_size], verbose_name='base_file'),
        ),
    ]
