# Generated by Django 3.2.13 on 2022-08-21 23:55

import collectdata.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0005_alter_basedata_base_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedata',
            name='base_file',
            field=models.FileField(upload_to='mydocs/', validators=[collectdata.validators.validate_file_size, collectdata.validators.validate_file_extention], verbose_name='base_file'),
        ),
    ]
