# Generated by Django 3.2.13 on 2022-08-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0006_alter_basedata_base_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedata',
            name='refine_file',
            field=models.FileField(blank=True, null=True, upload_to='mydocs/', verbose_name='refine_file'),
        ),
    ]
