# Generated by Django 3.2.13 on 2022-09-02 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0008_savedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
