# Generated by Django 3.2.13 on 2022-09-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0010_rename_save_savedata_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedata',
            old_name='saved',
            new_name='saved_data',
        ),
    ]
